region                          = "ap-south"
cidr_block                      = "10.0.0.0/16"
ami                             = "ami-0e35ddab05955cf57"
instance_type                   = "t2.micro"
availability_zone_public_subnet = "ap-south-1a"
publicSubnet_cidr_block         = "10.0.1.0/24"
